version: "3.2"
services:

  db:
    restart: always
    image: postgres:14.2
    environment:
      - MYSQL_HOST=ec2-63-32-248-14.eu-west-1.compute.amazonaws.com
      - MYSQL_PORT=5432
      - MYSQL_DATABASE=dav9fgm4nslook
      - MYSQL_USER=tiooyxbjoeppca
      - MYSQL_PASSWORD=63786f7807ddfbdb0f3286f7c2c479d44915650d0a57b3fce78f3b6316e14b36
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - db-net

  django:
    restart: always
    container_name: back
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8080"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django
    networks:
      - db-net

networks:
  db-net:
    driver: bridge